services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - '.env'
    ports:
      - '5050:80'
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
