services:
  postgres.idea:
    container_name: postgres
    image: postgres:16-alpine
    env_file: '.env'
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - idea-network

  idea:
    container_name: idea
    depends_on:
      - postgres.idea
    restart: always
    image: arch-idea:latest
    env_file:
      - '.env'
    ports:
      - 3000:3000
    networks:
      - idea-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - '.env'
    ports:
      - '5050:80'
    networks:
      - idea-network

networks:
  idea-network:
    driver: bridge

volumes:
  idea:
