//Модуль Идеи

@Host= localhost
@Port= 3000

@ApiKey = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbTU2djk1OXAwMDAxczd0NTdicnNnYzZtIiwicm9sZSI6IlVzZXIiLCJkZXBhcnRtZW50IjoiUGFybmFzIiwiaWF0IjoxNzM1MzEwODEzLCJleHAiOjE3MzYxNzQ4MTN9.0gZ-59aWjsdRlXpA0LEcoY9mTz2bBGAMQv145GcyJL8
Content-Type: application/json
Authorization: {{ApiKey}}

###


POST http://{{Host}}:{{Port}}/api/dislike/cm574d89z000fs7rsm70l7wgv HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}
###

