//Модуль Идеи

@Host= localhost
@Port= 3000

@ApiKey = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbTVmMXBycXQwMDAxczdkZzBzdXljZ3lnIiwicm9sZSI6IlVzZXIiLCJkZXBhcnRtZW50IjoiUGFybmFzIiwiaWF0IjoxNzM1ODA1Mzk2LCJleHAiOjE3MzU4NDEzOTZ9.UCvxpeYsNlNrE8yWWvmSTMpeHbE3LUJ2VfCCBdbpGxw
Content-Type: application/json
Authorization: {{ApiKey}}

###


POST  http://{{Host}}:{{Port}}/api/dislike/cm5e9hyrl0009s7hm3dcmy0kv HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}
###

