//Модуль Идеи

@Host= localhost
@Port= 3000

@ApiKey = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbTR4eDVsZmswMDAxczdmZXVzM3UxcG4xIiwicm9sZSI6InVzZXIiLCJkZXBhcnRtZW50Ijoi0J_QsNGA0L3QsNGBIiwiaWF0IjoxNzM0NzY5ODExLCJleHAiOjE3MzU2MzM4MTF9.BZgwLSJtKIFWGle2y1TqTP2pTXOJEZyj9iRjA0PLvcM
# @name newIdea
POST http://{{Host}}:{{Port}}/api/comment/cm4xys2ot0001s73igfzmwv9k HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

{
   "content": "Hello world"
}
###


GET http://{{Host}}:{{Port}}/api/comment/cm4xys2ot0001s73igfzmwv9k HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}
###
