//Модуль Идеи

@Host= localhost
@Port= 3000

@ApiKey = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbTU3OW1iaXgwMDAwczdiNmk1ZGdxbGxnIiwicm9sZSI6IlVzZXIiLCJkZXBhcnRtZW50IjoiUGFybmFzIiwiaWF0IjoxNzM1MzM0OTQyLCJleHAiOjE3MzYxOTg5NDJ9.5J9SPkT8nPBJZmXdFDf2hEcj6rw7uux7pUdcNQfzvck

GET   http://{{Host}}:{{Port}}/api/user/account HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

###