//Модуль Идеи

@Host= localhost
@Port= 3000

@ApiKey = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbTVlMjF4dXgwMDAzczc5cDRueXZzeHVrIiwicm9sZSI6IlVzZXIiLCJkZXBhcnRtZW50IjoiUGFybmFzIiwiaWF0IjoxNzM1NzQ1NDk4LCJleHAiOjE3MzU3ODE0OTh9.Grecgkrko6zdki-iyCAuRuEvmAoubScwPuP2tBerMRk

GET   http://{{Host}}:{{Port}}/api/user/account HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

###

GET   http://{{Host}}:{{Port}}/api/user/all HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

###