//Модуль Идеи

@Host= localhost
@Port= 3000

@ApiKey = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbTVxbzIzbG8wMDAxczdjaTM2NWhrdGk0Iiwicm9sZSI6IlVzZXIiLCJkZXBhcnRtZW50IjoiUGFybmFzIiwiaWF0IjoxNzM2NTA4MTkxLCJleHAiOjE3MzY1MDgyNTF9.WePmc7OEr-0uTvr7wr4FyFrjLcCeCTio6PY_J_sF42M

GET   http://{{Host}}:{{Port}}/api/user/account HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

###

GET   http://{{Host}}:{{Port}}/api/user/all HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

###