//Модуль Идеи

@Host= localhost
@Port= 3000

@ApiKey = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbTRzc2hpM2gwMDAxczcwN3V1MDg5MGJlIiwicm9sZSI6InVzZXIiLCJkZXBhcnRtZW50Ijoi0J_QsNGA0L3QsNGBIiwiaWF0IjoxNzM0NDU5NjM4LCJleHAiOjE3MzQ0OTU2Mzh9.olGyGOd-Tmppy2VH4k4gDhJMsivXEBdYKMqsJtSR7MQ

# @name newIdea
POST http://{{Host}}:{{Port}}/api/idea/create HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

{
    "title": "Парнас",
    "description":"Парнас",
    "userId": "",
    "department": "",
    "subDepartment": "Склад",
    "priority": "Низкий"
}
###


GET http://{{Host}}:{{Port}}/api/idea?limit=2&page=2 HTTP/1.1
Content-Type: application/json

###