//Модуль Идеи

@Host= localhost
@Port= 3000

@ApiKey = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbTU3OW1iaXgwMDAwczdiNmk1ZGdxbGxnIiwicm9sZSI6IlVzZXIiLCJkZXBhcnRtZW50IjoiUGFybmFzIiwiaWF0IjoxNzM1MzM0OTQyLCJleHAiOjE3MzYxOTg5NDJ9.5J9SPkT8nPBJZmXdFDf2hEcj6rw7uux7pUdcNQfzvck
# @name newIdea
POST http://{{Host}}:{{Port}}/api/idea/create HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

{
  "title": "New Idea",
  "description": "So far, Im just hearing a factual depiction of whats happening here.",
  "department": "Parnas",
  "subDepartment": "SalesFloor",
  "priority": "Medium"
}
###


GET http://{{Host}}:{{Port}}/api/idea?limit=100&department=Parnas HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}
###

GET http://{{Host}}:{{Port}}/api/idea/my-ideas?limit=100&sortDirection=desc HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}
###

GET http://{{Host}}:{{Port}}/api/idea/favorite-ideas?limit=100&sortDirection=desc HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}
###

GET http://{{Host}}:{{Port}}/api/idea/cm4ztvonw0003s796wbzaj4xd HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}
###


GET   http://{{Host}}:{{Port}}/api/idea/favorite HTTP/1.1
Content-Type: application/json
Authorization: {{ApiKey}}

{
    "id": "cm4ztvonw0003s796wbzaj4xd"
}
###
