//Модуль Регистрации


@Host=localhost
@Port= 3000

# @name department
POST http://{{Host}}:{{Port}}/api/department/create HTTP/1.1
Content-Type: application/json

{
    "title": "Parnas"
}
###

///$2b$10$xT.pqdkKWFsWxeI0NbsqFeXS0yNI/oWp9mkh1S8WnL.64jGM5dqf.

GET  http://{{Host}}:{{Port}}/api/department HTTP/1.1
Content-Type: application/json

###

# @ApiKey = {{department.response.body.qrCodeHash}}
@ApiKey = $2b$10$KHEEB6cvDq1ALQWR59ljrefDttkGk/qAmo3KPdm/5ResLUEFXenjG



# @name register 
POST http://{{Host}}:{{Port}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "sub": "{{ApiKey}}",
    "modelName": "Ipnohe"
}

###

@ApiKey2 = {{register.response.body.refresh_token}}
POST http://{{Host}}:{{Port}}/api/auth/refresh HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ApiKey2}}
###